server:
  port: 8081
  servlet:
    context-path: /ms-cours

spring:
  boot:
    admin:
      client:
        url: http://localhost:8997


management:
  health:
    show-details: always
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
