spring:
  application:
    name: video_call_app

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: khaled
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect