server:
  port: 7778
  servlet:
    context-path: /proxy

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: proxy
  boot:
    admin:
      client:
        url: http://localhost:8997
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true


management:
  health:
    show-details: always
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
