server:
  port: 8888
  servlet:
    context-path: /video_call_app

spring:
  application:
    name: video_call_app
  boot:
    admin:
      client:
        url: http://localhost:8997

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: khaled
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


management:
  health:
    show-details: always
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
