server:
  port: 8888
  servlet:
    context-path: /eureka-server

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:8997


management:
  health:
    show-details: always
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
